In [3]:
import pandas as pd
from pathlib import Path

In [5]:
# Load data
file_path = Path("../data/columns_final_df.json")
df = pd.read_json(file_path)

In [6]:
df.head()

,Year,Rank,Title,Artist,First Feature,Second Feature,Genres,Duration,Popularity,Spotify ID
0,2006,1,Bad Day,Daniel Powter,None,None,,3:53,71.0,0mUyMawtxj1CJ76kn9gIZK
1,2006,2,Temperature,Sean Paul,None,None,,3:38,78.0,0k2GOhqsrxDTAbFFSdNJjT
2,2006,3,Promiscuous,Nelly Furtado,Timbaland,None,,4:02,83.0,2gam98EZKrF9XuOkU13ApN
3,2006,4,You're Beautiful,James Blunt,None,None,,3:29,73.0,0vg4WnUWvze6pBOJDTq99k
4,2006,5,Hips Don't Lie (feat. Wyclef Jean),Shakira,Wyclef Jean,None,,3:38,84.0,3ZFTkvIE7kyPt6Nu3PEa7V

In [14]:
#Count the Total Number of Unique Artists
df['Artist'].nunique()

633

In [25]:
# Find the Top 10 Artists with the most Hot 100 songs
df['Artist'].value_counts().head(11)

Artist
Drake            43
Taylor Swift     36
Rihanna          32
Chris Brown      23
Maroon 5         22
Ariana Grande    22
Post Malone      19
Morgan Wallen    18
The Weeknd       18
Beyonc√©          18
Katy Perry       18
Name: count, dtype: int64

In [13]:
#Find Number of One Hit Wonders

#Set Count of each artist into a Variable
artist_counts = df['Artist'].value_counts()

#Filter for Artists who only appear once as the Recording Artist and Count them
one_hit_wonders = artist_counts[artist_counts ==1]
one_hit_wonders.count()

320

In [52]:
#Find Top 10 Artists with Most Primary Features
df['First Feature'].value_counts().head(10)

First Feature
Drake            33
T-Pain           14
Nicki Minaj      14
Rihanna          13
Lil Wayne        13
Justin Bieber    10
21 Savage         9
Akon              9
Chris Brown       9
Kanye West        8
Name: count, dtype: int64

In [45]:
# Find How Many Total Hits Drake Has
drake_df = df.loc[(df["Artist"] == "Drake") | (df["First Feature"] == "Drake") 
| (df["Second Feature"] == "Drake"), :]
drake_df

,Year,Rank,Title,Artist,First Feature,Second Feature,Genres,Duration,Popularity,Spotify ID
321,2009,22,Best I Ever Had,Drake,None,None,,4:17,74.0,3QLjDkgLh9AOEHlhQtDuhs
387,2009,88,Forever,Drake,Kanye West,Lil Wayne,,5:57,73.0,5UsLjwBaTHBX4ektWIr4XX
431,2010,32,Find Your Love,Drake,None,None,,3:28,63.0,4BycRneKmOs6MhYG9THsuX
459,2010,60,Over,Drake,None,None,,3:53,66.0,6BdgtqiV3oXNqBikezwdvC
470,2010,71,Forever,Drake,Kanye West,Lil Wayne,,5:57,73.0,5UsLjwBaTHBX4ektWIr4XX
...,...,...,...,...,...,...,...,...,...,...
1796,2023,97,MELTDOWN (feat. Drake),Travis Scott,Drake,None,,4:06,74.0,67nepsnrcZkowTxMWigSbb
1844,2024,45,Rich Baby Daddy (feat. Sexyy Red & SZA),Drake,Sexyy Red,SZA,,5:19,78.0,1yeB8MUNeLo9Ek1UEpsyz6
1860,2024,61,First Person Shooter (feat. J. Cole),Drake,J. Cole,None,,4:07,73.0,7aqfrAY2p9BUSiupwk3svU
1879,2024,80,act ii: date @ 8 (feat. Drake) - remix,4batz,Drake,None,,3:51,70.0,3QS9ZCtoSCJhmaJ7QNXSAS
1882,2024,83,IDGAF (feat. Yeat),Drake,Yeat,None,,4:20,75.0,2YSzYUF3jWqb9YP9VXmpjE

In [43]:
#Find Total Hits for Drake
total_hits = drake_df.shape[0]
total_hits

76